services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_induccion
      MYSQL_ROOT_PASSWORD: ${INDUCCION_DB_PW}
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
